[platformio]
default_envs = compile-check
src_dir = examples/BasicClient

[env:compile-check]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 748800
lib_extra_dirs = .
build_flags =
    -D CORE_DEBUG_LEVEL=1
